### ISSUE TITLE
Use of hydra.utils.instantiate

### ISSUE THREAD

**Issue by fdroessler** [Erlemar/pytorch_tempest#43]
Hi really like your template! Thanks for putting it out there.

I was wondering what your thoughts are on using hydras coming [instantiate](https://hydra.cc/docs/next/patterns/instantiate_objects/overview/) feature vs. the `load_obj`? Have you had a look at it or played around with it? It seems to work for me in some cases but can also cause weird effects. Would be curious on your thoughts.

**Comment by Erlemar** [comment]
Hello! I'm glad you like it!

I have looked at `instantiate` several months ago, tried to apply it to my project and decided that `load_obj` works better in my case, the main reason being flexibility.

Here are some possible problems:
* changing to `instantiate` this requires rewriting all configs and changing the loading from `instantiate` to `load_obj`
* in some cases I initialize objects inside other classes. For example encoder and decoder in model or model and metric in main lightning class. The recommended approach in hydra is recursive instantiation, but it requires a specific template for configuration files and I don't want to do it. So I use basic hydra in such cases
* when I'm working on projects at my job, often I use some configuration files while making predictions. If possible it is better not to use unnecessary additional libraries in this case

**Comment by fdroessler** [comment]
Thanks for that :)
