### ISSUE TITLE
protobuf crash

### ISSUE THREAD

**Issue by lolaclinton** [Erlemar/pytorch_tempest#44]
HI- Thanks for putting this out there. I would love to see your refinements.
Currently I'm trying to run the MNIST example you have in the README and I'm getting the following crash when it tries to load the data. I tried changing the protobuf version a few times but it didn't seem to matter (v 3.8, 3.14, 3.11)

[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:393] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1367] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):

**Comment by Erlemar** [comment]
This is an interesting problem. I assume you use Mac OS?
I hope these links will help:
https://github.com/tensorflow/tensorflow/issues/33746
https://github.com/tensorflow/tensorflow/issues/35573
https://github.com/onnx/onnx/issues/2808
